spring:
  data:
    mongodb:
      uri: mongodb+srv://shubhankarpotnisofficial_db_user:0cDThRdpXy3LH0sY@cluster001.yzm9yz3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster001
      database: Testing
      auto-index-creation: true

server:
  port: ${PORT:8085}
  servlet:
    context-path: /diary

jwt:
  secret: qoike6n0nTbyk4qtu7nxSRjn1duCeu1Td8i5p0AT3Z4=
  access-expiry-ms: 900000