spring:
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
  servlet:
    context-path: /diary

jwt:
  access-expiry-ms: 900000